### ISSUE TITLE
External Nginx Proxy Manager

### ISSUE THREAD

**Issue by Psens666** [opengisch/QFieldCloud#1032]
Hello,

i comment out the nginx in docker-compose file, because a have already running an nginx proxy manager instance, i can connect to the webinterface but if i wand to download a file from the webinterface or a projcet in the app i got an 500 error.

My instance is cofig local.

My nginx config is http://qflield.xxxxxx.org to port http://10.0.0.4:8011 where the app is available. what else have i to config that the download works?

**Comment by suricactus** [comment]
@Psens666 thank you for testing out QFieldCloud.

We do not offer the possibility to run QFieldCloud with external nginx as for now. That's why we provided the docker-compose.yml file, that offers plug-n-play QFieldCloud deployment, as well as example in case you really insist to run nginx on your own.

I am closing this, as it is not an upstream issue.
