### ISSUE TITLE
What config-fields need to be set?

### ISSUE THREAD

**Issue by bastooo** [opengisch/qfieldcloud#175]
First of all, I'm very happy and appreciate the fact, that people/organizations like you exist and create something open for the community! I would like to setup QFieldCloud on my server to check out, if I can use it together with QField for mapping e.g. fauna. My problem is, that I'm not quite sure how to setup the config-file `.env`?

In the Readme.md you just wrote: 

> Copy the .env.example into .env file and configure it to your desire

But what does this exactly mean? Like:

1. Do I need to setup a PostgreSQL-server, which will be used by the QfieldCloud or is there a predefined docker-image from you? Which I don't need to touch?
2. It's the same about Redis? Do I need to setup Redis on the server or will it be handled by any docker-image?
3. What ports do I need to open in the firewall?
4. I think it's wise to change the predefined passwords in the file or will it brake any internal procedures?
5. Do I need to setup the E-Mail config to try out QfieldCloud?

Furthermore: do I need to change something in the `docker-compose.override.yml` or any other config-file?

Greetings

**Comment by suricactus** [comment]
Hello, @bastooo . Thanks for checking out QFieldCloud! 

You pretty much nailed it - if you copy-paste `.env.example`  and rename `docker-compose.override.local.yml` to `docker-compose.override.yml` it should just run. Then you can incrementally replace the services you use. This is how development and tests are being run, check here https://github.com/opengisch/qfieldcloud/blob/master/.github/workflows/test.yml#L26-L37 .

> Do I need to setup a PostgreSQL-server, which will be used by the QfieldCloud or is there a predefined docker-image from you? Which I don't need to touch?
In `docker-compose.yml` and `docker-compose.override.local.yml` you have everything you will ever need to run QFieldCloud.

> It's the same about Redis? Do I need to setup Redis on the server or will it be handled by any docker-image?
What ports do I need to open in the firewall?
Currently redis is not used in QFieldCloud, even though it is a dependency. Very soon we will reintegrate it in the app.

> I think it's wise to change the predefined passwords in the file or will it brake any internal procedures?
Do I need to setup the E-Mail config to try out QfieldCloud?

Would be nice to change you passwords, otherwise you may experience problems. You will need to configure an email provider for sure.

Hope it answers your questions.
