### ISSUE TITLE
Challenges in Setting Up QFieldCloud in Production Environment

### ISSUE THREAD

**Issue by MoritzPatek** [opengisch/qfieldcloud#841]
#### Description
I am attempting to deploy QFieldCloud in a production environment but am encountering several challenges, primarily due to inadequate documentation.

#### Issue Details
- **Production Environment Setup:** Successfully building QFieldCloud in a local environment, but facing difficulties in the production environment setup.
- **Documentation:** Current documentation appears to be incomplete or unclear, especially regarding the setup and configuration for the production environment.
- **Storage Options:** Unclear how to properly configure storage options (e.g., S3) for QFieldCloud, as S3 storages are not typically used for databases.
- **Postgres Docker Image:** The Postgres Docker image does not seem to be included in the production environment build, leading to a lack of database access.
- **Integration with QGIS:** Experiencing issues when trying to connect QFieldCloud with QGIS using the extension. This might be due to Docker container configuration rather than the program itself.

#### Configurations
Key configurations from my `.env` file include:
- `ENVIRONMENT=production`
- `DEBUG=0`
- Database configurations: `POSTGRES_*`
- Storage configurations: `STORAGE_*`, with particular attention to `STORAGE_ENDPOINT_URL=http://172.17.0.1:9000`
- Web server ports: `WEB_HTTP_PORT=80`, `WEB_HTTPS_PORT=443`
- `QFIELDCLOUD_HOST=localhost`
- `DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1 0.0.0.0 app nginx"`

#### Attempts
- No specific error messages have been encountered; the issues seem to stem from configuration and setup challenges.

#### Request
Guidance on setting up QFieldCloud in a production environment is sought, along with clear, step-by-step documentation, particularly regarding database setup and integration with QGIS.

**Comment by stcz** [comment]
#844 might be interesting for you.

**Comment by suricactus** [comment]
Hello @MoritzPatek , thanks for using QFieldCloud. Let me try to answer your questions below.

> * **Documentation:** Current documentation appears to be incomplete or unclear, especially regarding the setup and configuration for the production environment.

Our own production QFieldCloud deployment is based entirely on `docker-compose.yml` and `docker-compose.override.prod.yml` with some additional extras on top, specific for app.qfield.cloud.
 
If you find any particular sections that are not well documented, feel free to open a PR. Contributions are more than welcome. You can find documentation about QFieldCloud in both the `README.md` and on https://docs.qfield.org . 

> * **Storage Options:** Unclear how to properly configure storage options (e.g., S3) for QFieldCloud, as S3 storages are not typically used for databases.

It seems there is misunderstanding, the object storage (S3) is not used for the classical meaning of database. S3 is used to store the project files (.qgs file, GeoPackage, images etc).

The object storage is expected to be an external service due to complexity in managing the service for production environments.

> * **Postgres Docker Image:** The Postgres Docker image does not seem to be included in the production environment build, leading to a lack of database access.

PostgreSQL is expected to be an external service due to complexity in managing the service for production environments.

> * **Integration with QGIS:** Experiencing issues when trying to connect QFieldCloud with QGIS using the extension. This might be due to Docker container configuration rather than the program itself.

Cannot tell anything without any particular reproducible example what is not working.

> #### Configurations
> Key configurations from my `.env` file include:
> 
> * `ENVIRONMENT=production`
> * `DEBUG=0`
> * Database configurations: `POSTGRES_*`
> * Storage configurations: `STORAGE_*`, with particular attention to `STORAGE_ENDPOINT_URL=http://172.17.0.1:9000`
> * Web server ports: `WEB_HTTP_PORT=80`, `WEB_HTTPS_PORT=443`
> * `QFIELDCLOUD_HOST=localhost`
> * `DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1 0.0.0.0 app nginx"`

At first glance there is nothing suspicious in your configuration. However, there are multiple variables in the `.env` that might cause problems with your particular setup.

> #### Request
> Guidance on setting up QFieldCloud in a production environment is sought, along with clear, step-by-step documentation, particularly regarding database setup and integration with QGIS.

As I already stated, we are more than happy for contributions to improve our documentation.

If you need dedicated support for your on-premise setup, please let us know on sales@qfield.cloud.

Hope it helps!
