### ISSUE TITLE
DOCKER_ENGINE_SIGKILL

### ISSUE THREAD

**Issue by nesar77** [opengisch/qfieldcloud#926]
I'm working on a small project (less than 100MB) and I'm not able to sync the project on my mobile (android phone) because I'm getting the following error:

{
  "error": "Docker engine sigkill.",
  "error_class": "",
  "error_origin": "container",
  "error_stack": "",
  "error_type": "DOCKER_ENGINE_SIGKILL"
}

Using QGis Desktop it works like a charme.

The qfield-worker-wrapper contains:

{"request_id":"none","ts":"2024-04-11T12:29:59.207717","level":"INFO","name":"worker_wrapper.wrapper","message":"Execute: python3 entrypoint.py package 3711b2f2-3d5d-47a3-b94b-826d852cd6f2 Acquedotto_EditingDesktop-R02_cloud.qgs pythonmini","filename":"wrapper.py","lineno":283,"thread":139841327523648,"source":"worker_wrapper"}
{"request_id":"none","ts":"2024-04-11T12:29:59.596842","level":"INFO","name":"worker_wrapper.wrapper","message":"Starting worker c26d79632fe3531ae4d6f43b330f2a2b76158c95418454fe5a325c0a8c30d523 ...","filename":"wrapper.py","lineno":326,"thread":139841327523648,"source":"worker_wrapper"}
{"request_id":"none","ts":"2024-04-11T12:30:50.510433","level":"INFO","name":"worker_wrapper.wrapper","message":"Job canceled, probably due to deleted Project and Jobs.","filename":"wrapper.py","lineno":335,"thread":139841327523648,"source":"worker_wrapper"}
{"request_id":"none","ts":"2024-04-11T12:30:50.514042","level":"INFO","name":"worker_wrapper.wrapper","message":"Set job status to `failed` due to being killed by the docker engine.","filename":"wrapper.py","lineno":164,"thread":139841327523648,"source":"worker_wrapper"}

**Comment by suricactus** [comment]
I suppose you are using a QFieldCloud on premise and not app.qfield.cloud? If on premise what version are you using? Have you tried with the latest QFieldCloud release? Can you attach a sample project?

**Comment by EgidijusViko** [comment]
Hello, have same issue. Yes it is releated with self-hosted solution. Also getting same error.

worker_wrapper-1               | {"request_id":"none","ts":"2024-04-23T11:38:21.776971","level":"INFO","name":"worker_wrapper.wrapper","message":"Job canceled, probably due to deleted Project and Jobs.","filename":"wrapper.py","lineno":335,"thread":131536224319296,"source":"worker_wrapper"}
db-1                           | 2024-04-23 11:38:21.782 UTC [30] LOG:  statement: UPDATE "core_job" SET "status" = 'failed', "output" = 'Job has been cancelled by parent process!', "feedback" = '{"error": "Docker engine sigkill.", "error_type": "DOCKER_ENGINE_SIGKILL", "error_class": "", "error_origin": "container", "error_stack": ""}' WHERE "core_job"."id" = 'fe0c9e1c-4278-40c7-94a2-548c54fa427e'::uuid
db-1                           | 2024-04-23 11:38:21.786 UTC [30] LOG:  statement: COMMIT
worker_wrapper-1               | {"request_id":"none","ts":"2024-04-23T11:38:21.789491","level":"INFO","name":"worker_wrapper.wrapper","message":"Set job status to `failed` due to being killed by the docker engine.","filename":"wrapper.py","lineno":164,"thread":131536224319296,"source":"worker_wrapper"}
festive_dijkstra exited with code 137

**Comment by nesar77** [comment]
Hi @EgidijusViko 
the error depends on the memory limit set in the settings.py file; the parameter name is WORKER_QGIS_MEMORY_LIMIT. For large projects, try to increasing this valut to 1.5G or resize your project.

**Comment by EgidijusViko** [comment]
@nesar77 You mean this one settings in QFieldCloud admin site? The restart of qfieldcloud instance is needed?
![image](https://github.com/opengisch/qfieldcloud/assets/55689250/a42ea460-f512-48e2-b646-fa2c46136610)

**Comment by nesar77** [comment]
I think so

**Comment by suricactus** [comment]
Yes, set the value as in the screenshot and restart your docker compose setup. @nesar77 thanks for confirming this solved the issue for you.
